/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DateFrame.java
 *
 * Created on Jul 4, 2011, 12:20:47 PM
 */

package clubdoors;

/**
 *
 * @author Devin
 */
public class DateFrame extends javax.swing.JFrame {

    /** Creates new form DateFrame */
    public DateFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monthBox = new javax.swing.JComboBox();
        dayBox = new javax.swing.JComboBox();
        yearBox = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        yearBoxTo = new javax.swing.JComboBox();
        dayBoxTo = new javax.swing.JComboBox();
        monthBoxTo = new javax.swing.JComboBox();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        monthBox.setFont(new java.awt.Font("Tahoma", 0, 18));
        monthBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthBox.setName("monthBox"); // NOI18N

        dayBox.setFont(new java.awt.Font("Tahoma", 0, 18));
        dayBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayBox.setName("dayBox"); // NOI18N

        yearBox.setFont(new java.awt.Font("Tahoma", 0, 18));
        yearBox.setName("yearBox"); // NOI18N

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Sumbit");
        submitButton.setName("submitButton"); // NOI18N

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N

        yearBoxTo.setFont(new java.awt.Font("Tahoma", 0, 18));
        yearBoxTo.setName("yearBoxTo"); // NOI18N

        dayBoxTo.setFont(new java.awt.Font("Tahoma", 0, 18));
        dayBoxTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayBoxTo.setName("dayBoxTo"); // NOI18N

        monthBoxTo.setFont(new java.awt.Font("Tahoma", 0, 18));
        monthBoxTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthBoxTo.setName("monthBoxTo"); // NOI18N

        fromLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        fromLabel.setText("From:");
        fromLabel.setName("fromLabel"); // NOI18N

        toLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        toLabel.setText("To:");
        toLabel.setName("toLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fromLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(monthBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dayBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yearBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromLabel))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelButton;
    public javax.swing.JComboBox dayBox;
    public javax.swing.JComboBox dayBoxTo;
    public javax.swing.JLabel fromLabel;
    public javax.swing.JComboBox monthBox;
    public javax.swing.JComboBox monthBoxTo;
    public javax.swing.JButton submitButton;
    public javax.swing.JLabel toLabel;
    public javax.swing.JComboBox yearBox;
    public javax.swing.JComboBox yearBoxTo;
    // End of variables declaration//GEN-END:variables

    /**
     * Resets the variables to the originally selected
     */
    public void reset(){
        this.monthBox.setSelectedIndex(0);
        this.dayBox.setSelectedIndex(0);
        this.yearBox.setSelectedIndex(5);

        this.monthBoxTo.setSelectedIndex(0);
        this.dayBoxTo.setSelectedIndex(0);
        this.yearBoxTo.setSelectedIndex(5);
    }

    /**
     * Returns the values of from and to in a string
     * @return String from-to
     */
    public String getFromTo(){
        String fMonth =
                Integer.toString(this.monthBox.getSelectedIndex() + 1);
        String fDay = this.dayBox.getSelectedItem().toString();
        String fYear = this.yearBox.getSelectedItem().toString();

        String tMonth =
                Integer.toString(this.monthBoxTo.getSelectedIndex() + 1);
        String tDay = this.dayBoxTo.getSelectedItem().toString();
        String tYear = this.yearBoxTo.getSelectedItem().toString();

        return fMonth + "/" + fDay + "/" + fYear + " - "
                + tMonth + "/" + tDay + "/" + tYear;
    }

    /**
     * Returns the int values selected as the from date
     * @return int[] from
     */
    public int[] getFrom(){
        int month = this.monthBox.getSelectedIndex() + 1;
        int day =
                Integer.parseInt(this.dayBox.getSelectedItem().toString());
        int year =
                Integer.parseInt(this.yearBox.getSelectedItem().toString());

        return new int[]{month, day, year};
    }

    /**
     * Returns the int values selected as the to date
     * @return int[] to
     */
    public int[] getTo(){
        int month = this.monthBoxTo.getSelectedIndex() + 1;
        int day =
                Integer.parseInt(this.dayBoxTo.getSelectedItem().toString());
        int year =
                Integer.parseInt(this.yearBoxTo.getSelectedItem().toString());

        return new int[]{month, day, year};
    }
}
