package clubdoors;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPanel.java
 *
 * Created on May 6, 2011, 1:39:00 PM
 */

/**
 *
 * @author Devin
 */
public class MainPanel extends javax.swing.JPanel {

    /** Creates new form MainPanel */
    public MainPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fiveButton = new javax.swing.JButton();
        tenButton = new javax.swing.JButton();
        twentyButton = new javax.swing.JButton();
        gameButton = new javax.swing.JButton();
        managerButton = new javax.swing.JButton();
        compButton = new javax.swing.JButton();
        doorButton = new javax.swing.JButton();
        numField = new javax.swing.JTextField();
        reportsButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        numLabel = new javax.swing.JLabel();
        hotelButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));

        fiveButton.setBackground(new java.awt.Color(0, 0, 0));
        fiveButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fiveButton.setForeground(new java.awt.Color(255, 255, 255));
        fiveButton.setText("$5");
        fiveButton.setName("fiveButton"); // NOI18N

        tenButton.setBackground(new java.awt.Color(0, 0, 0));
        tenButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tenButton.setForeground(new java.awt.Color(255, 255, 255));
        tenButton.setText("$10");
        tenButton.setName("tenButton"); // NOI18N

        twentyButton.setBackground(new java.awt.Color(0, 0, 0));
        twentyButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        twentyButton.setForeground(new java.awt.Color(255, 255, 255));
        twentyButton.setText("$20");
        twentyButton.setName("twentyButton"); // NOI18N

        gameButton.setBackground(new java.awt.Color(0, 0, 0));
        gameButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gameButton.setForeground(new java.awt.Color(255, 255, 255));
        gameButton.setText("G-Tix");
        gameButton.setName("gameButton"); // NOI18N

        managerButton.setBackground(new java.awt.Color(0, 0, 0));
        managerButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        managerButton.setForeground(new java.awt.Color(255, 255, 255));
        managerButton.setText("Mgr comp"); // NOI18N
        managerButton.setName("managerButton"); // NOI18N

        compButton.setBackground(new java.awt.Color(0, 0, 0));
        compButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compButton.setForeground(new java.awt.Color(255, 255, 255));
        compButton.setText("Comp Pass"); // NOI18N
        compButton.setName("compButton"); // NOI18N

        doorButton.setBackground(new java.awt.Color(0, 0, 0));
        doorButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        doorButton.setForeground(new java.awt.Color(255, 255, 255));
        doorButton.setText("Comp");
        doorButton.setName("doorButton"); // NOI18N

        numField.setName("numField"); // NOI18N

        reportsButton.setBackground(new java.awt.Color(0, 0, 0));
        reportsButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        reportsButton.setForeground(new java.awt.Color(255, 255, 255));
        reportsButton.setText("Reports");
        reportsButton.setName("reportsButton"); // NOI18N

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 10));
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("Number of prints may not exceed 20");
        errorLabel.setName("errorLabel"); // NOI18N

        seven.setBackground(new java.awt.Color(0, 0, 0));
        seven.setForeground(new java.awt.Color(255, 255, 255));
        seven.setText("7");
        seven.setName("seven"); // NOI18N

        eight.setBackground(new java.awt.Color(0, 0, 0));
        eight.setForeground(new java.awt.Color(255, 255, 255));
        eight.setText("8");
        eight.setName("eight"); // NOI18N

        nine.setBackground(new java.awt.Color(0, 0, 0));
        nine.setForeground(new java.awt.Color(255, 255, 255));
        nine.setText("9");
        nine.setName("nine"); // NOI18N

        four.setBackground(new java.awt.Color(0, 0, 0));
        four.setForeground(new java.awt.Color(255, 255, 255));
        four.setText("4");
        four.setName("four"); // NOI18N

        five.setBackground(new java.awt.Color(0, 0, 0));
        five.setForeground(new java.awt.Color(255, 255, 255));
        five.setText("5");
        five.setName("five"); // NOI18N

        six.setBackground(new java.awt.Color(0, 0, 0));
        six.setForeground(new java.awt.Color(255, 255, 255));
        six.setText("6");
        six.setName("six"); // NOI18N

        one.setBackground(new java.awt.Color(0, 0, 0));
        one.setForeground(new java.awt.Color(255, 255, 255));
        one.setText("1");
        one.setName("one"); // NOI18N

        two.setBackground(new java.awt.Color(0, 0, 0));
        two.setForeground(new java.awt.Color(255, 255, 255));
        two.setText("2");
        two.setName("two"); // NOI18N

        three.setBackground(new java.awt.Color(0, 0, 0));
        three.setForeground(new java.awt.Color(255, 255, 255));
        three.setText("3");
        three.setName("three"); // NOI18N

        zero.setBackground(new java.awt.Color(0, 0, 0));
        zero.setForeground(new java.awt.Color(255, 255, 255));
        zero.setText("0");
        zero.setName("zero"); // NOI18N

        clearButton.setBackground(new java.awt.Color(0, 0, 0));
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.setName("clearButton"); // NOI18N

        numLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        numLabel.setText("#");
        numLabel.setName("numLabel"); // NOI18N

        hotelButton.setBackground(new java.awt.Color(0, 0, 0));
        hotelButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hotelButton.setForeground(new java.awt.Color(255, 255, 255));
        hotelButton.setText("Hotel");
        hotelButton.setName("hotelButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(errorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fiveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hotelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(compButton, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                            .addComponent(twentyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numField)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numLabel)
                    .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(errorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(gameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(twentyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(compButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(managerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton clearButton;
    public javax.swing.JButton compButton;
    public javax.swing.JButton doorButton;
    public javax.swing.JButton eight;
    public javax.swing.JLabel errorLabel;
    public javax.swing.JButton five;
    public javax.swing.JButton fiveButton;
    public javax.swing.JButton four;
    public javax.swing.JButton gameButton;
    public javax.swing.JButton hotelButton;
    public javax.swing.JButton managerButton;
    public javax.swing.JButton nine;
    public javax.swing.JTextField numField;
    public javax.swing.JLabel numLabel;
    public javax.swing.JButton one;
    public javax.swing.JButton reportsButton;
    public javax.swing.JButton seven;
    public javax.swing.JButton six;
    public javax.swing.JButton tenButton;
    public javax.swing.JButton three;
    public javax.swing.JButton twentyButton;
    public javax.swing.JButton two;
    public javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables


    /**
     * Clears the numField
     */
    public void clear(){
        this.numField.setText("");
    }

    /**
     * Adds the given number to the numField
     * @param i the integer to be added
     */
    public void add(int i){
        this.numField.setText(this.get() + Integer.toString(i));
    }

    /**
     * Gets the text in the numField
     * @return String numField text
     */
    public String get(){
        return this.numField.getText();
    }

    /**
     * Returns the integer value of the numField
     * or throws an error if it is over 20
     * @return
     */
    public int getNum() throws Exception{
        if(this.get().equals("")){return 1;}
        int i = Integer.parseInt(this.get());
        if(i>20){
            throw new Exception();
        }else{
            return i;
        }
    }
}
